#will have to add function to calculate percentage
#user should just input numbers


class AmenityStats():


	def __init__(self):
		self.accounting  = None
		self.airport = None
		self.amusement_park = None
		self.aquarium = None
		self.art_gallery = None
		self.atm = None
		self.bakery = None
		self.bank = None
		self.bar = None
		self.beauty_salon = None
		self.bicycle_store = None
		self.book_store = None
		self.bowling_alley = None
		self.bus_station = None
		self.cafe = None
		self.campground = None
		self.car_dealer = None
		self.car_rental = None
		self.car_repair = None
		self.car_wash = None
		self.casino = None
		self.cemetery = None
		self.church = None
		self.city_hall = None
		self.clothing_store = None
		self.convenience_store = None
		self.courthouse = None
		self.dentist = None
		self.department_store = None
		self.doctor = None
		self.electrician = None
		self.electronics_store = None
		self.embassy = None
		self.finance = None
		self.fire_station = None
		self.florist = None
		self.food = None
		self.funeral_home = None
		self.furniture_store = None
		self.gas_station = None
		self.general_contractor = None
		self.grocery_or_supermarket = None
		self.gym = None
		self.hair_care = None
		self.hardware_store = None
		self.health = None
		self.hindu_temple = None
		self.home_goods_store = None
		self.hospital = None
		self.insurance_agency = None
		self.jewelry_store = None
		self.laundry = None
		self.lawyer = None
		self.library = None
		self.liquor_store = None
		self.local_government_office = None
		self.locksmith = None
		self.lodging = None
		self.meal_delivery = None
		self.meal_takeaway = None
		self.mosque = None
		self.movie_rental = None
		self.movie_theater = None
		self.moving_company = None
		self.museum = None
		self.night_club = None
		self.painter = None
		self.park = None
		self.parking = None
		self.pet_store = None
		self.pharmacy = None
		self.physiotherapist = None
		self.place_of_worship = None
		self.plumber = None
		self.police = None
		self.post_office = None
		self.real_estate_agency = None
		self.restaurant = None
		self.roofing_contractor = None
		self.rv_park = None
		self.school = None
		self.shoe_store = None
		self.shopping_mall = None
		self.spa = None
		self.stadium = None
		self.storage = None
		self.store = None
		self.sublocality_level_1 = None 
		self.sublocality_level_2 = None
		self.sublocality_level_3 = None
		self.sublocality_level_4 = None
		self.sublocality_level_5 = None
		self.subway_station = None
		self.synagogue = None
		self.taxi_stand = None
		self.train_station = None
		self.travel_agency = None
		self.university = None
		self.veterinary_care = None
		self.zoo = None

		self.amenity_dict = None
		#self.createAmenityDict()

	def addAmenityStat(self, amenity_name, value):
		self.amenity_dict[amenity_name] = value

	def createAmenityDict(self):
		self.amenity_dict = {
			'accounting': self.accounting,
			'airport' : self.airport,
			'amusement_park' : self.amusement_park,
			'aquarium' : self.aquarium,
			'' : self.art_gallery,
			'' : self.atm,
			'' : self.bakery,
			'' : self.bank,
			'' : self.bar,
			'' : self.beauty_salon,
			'' : self.bicycle_store,
			'' : self.book_store,
			'' : self.bowling_alley,
			'' : self.bus_station,
			'' : self.cafe,
			'' : self.campground,
			'' : self.car_dealer,
			'' : self.car_rental,
			'' : self.car_repair,
			'' : self.car_wash,
			'' : self.casino,
			'' : self.cemetery,
			'' : self.church,
			'' : self.city_hall,
			'' : self.clothing_store,
			'' : self.convenience_store,
			'' : self.courthouse,
			'' : self.dentist,
			'' : self.department_store,
			'' : self.doctor,
			'' : self.electrician,
			'' : self.electronics_store,
			'' : self.embassy,
			'' : self.finance,
			'' : self.fire_station,
			'' : self.florist,
			'' : self.food,
			'' : self.funeral_home,
			'' : self.furniture_store,
			'' : self.gas_station,
			'' : self.general_contractor,
			'' : self.grocery_or_supermarket,
			'' : self.gym,
			'' : self.hair_care,
			'' : self.hardware_store,
			'' : self.health,
			'' : self.hindu_temple,
			'' : self.home_goods_store,
			'' : self.hospital,
			'' : self.insurance_agency,
			'' : self.jewelry_store,
			'' : self.laundry,
			'' : self.lawyer,
			'' : self.library,
			'' : self.liquor_store,
			'' : self.local_government_office,
			'' : self.locksmith,
			'' : self.lodging,
			'' : self.meal_delivery,
			'' : self.meal_takeaway,
			'' : self.mosque,
			'' : self.movie_rental,
			'' : self.movie_theater,
			'' : self.moving_company,
			'' : self.museum,
			'' : self.night_club,
			'' : self.painter,
			'' : self.park,
			'' : self.parking,
			'' : self.pet_store,
			'' : self.pharmacy,
			'' : self.physiotherapist,
			'' : self.place_of_worship,
			'' : self.plumber,
			'' : self.police,
			'' : self.post_office,
			'' : self.real_estate_agency,
			'' : self.restaurant,
			'' : self.roofing_contractor,
			'' : self.rv_park,
			'' : self.school,
			'' : self.shoe_store,
			'' : self.shopping_mall,
			'' : self.spa,
			'' : self.stadium,
			'' : self.storage,
			'' : self.store,
			'' : self.sublocality_level_1,
			'' : self.sublocality_level_2,
			'' : self.sublocality_level_3,
			'' : self.sublocality_level_4,
			'' : self.sublocality_level_5,
			'' : self.subway_station,
			'' : self.synagogue,
			'' : self.taxi_stand,
			'' : self.train_station,
			'' : self.travel_agency,
			'' : self.university,
			'' : self.veterinary_care,
			'' : self.zoo
		}





